DROP DATABASE IF EXISTS home_medic;
CREATE DATABASE home_medic;

CREATE TABLE tradesmen(
  id INT NOT NULL,
  name VARCHAR(100) NOT NULL
);
CREATE TABLE what_hurts(
  id INT NOT NULL,
  name VARCHAR(100) NOT NULL
);
CREATE TABLE sign up(
  id INT NOT NULL,
  name VARCHAR(100) NOT NULL
);